version: '3'
services:
  db:
    image: postgres
  elasticsearch:
    image: elasticsearch:1.7.1
    ports:
      - "9200:9200"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch